version: '3'

services:
  frontend-pancake-swap-interface:
    container_name: pancake-swap-interface
    image: "registry-server:5000/pancake-swap-interface"
    ports:
      - "8032:80"
    environment:
      REACT_APP_BASE_URL: https://citrus-api.sotatek.works
    volumes:
      - ./pancake-swap-interface:/app